type Participant = {
    id: string;
    name: string;
    email: string;
    semester: 'First' | 'Third';
  };

  export const participants: Participant[] = [
    { id: '1', name: 'Alice', email: 'alice@example.com', semester: 'First' },
    { id: '2', name: 'Bob', email: 'bob@example.com', semester: 'Third' },
    { id: '3', name: 'Charlie', email: 'charlie@example.com', semester: 'First' },
    { id: '4', name: 'David', email: 'david@example.com', semester: 'Third' },
    { id: '5', name: 'Eve', email: 'eve@example.com', semester: 'First' },
    { id: '6', name: 'Frank', email: 'frank@example.com', semester: 'Third' },
    { id: '7', name: 'Grace', email: 'grace@example.com', semester: 'First' },
    { id: '8', name: 'Hank', email: 'hank@example.com', semester: 'Third' },
    { id: '9', name: 'Ivy', email: 'ivy@example.com', semester: 'First' },
    { id: '10', name: 'Jack', email: 'jack@example.com', semester: 'Third' },
    { id: '11', name: 'Kate', email: 'kate@example.com', semester: 'First' },
    { id: '12', name: 'Liam', email: 'liam@example.com', semester: 'Third' },
    { id: '13', name: 'Mia', email: 'mia@example.com', semester: 'First' },
    { id: '14', name: 'Noah', email: 'noah@example.com', semester: 'Third' },
    { id: '15', name: 'Olivia', email: 'olivia@example.com', semester: 'First' },
    { id: '16', name: 'Peter', email: 'peter@example.com', semester: 'Third' },
    { id: '17', name: 'Quinn', email: 'quinn@example.com', semester: 'First' },
    { id: '18', name: 'Ryan', email: 'ryan@example.com', semester: 'Third' },
    { id: '19', name: 'Sophia', email: 'sophia@example.com', semester: 'First' },
    { id: '20', name: 'Tom', email: 'tom@example.com', semester: 'Third' },
    { id: '21', name: 'Uma', email: 'uma@example.com', semester: 'First' },
    { id: '22', name: 'Victor', email: 'victor@example.com', semester: 'Third' },
    { id: '23', name: 'Wendy', email: 'wendy@example.com', semester: 'First' },
    { id: '24', name: 'Xander', email: 'xander@example.com', semester: 'Third' },
    { id: '25', name: 'Yara', email: 'yara@example.com', semester: 'First' },
    { id: '26', name: 'Zane', email: 'zane@example.com', semester: 'Third' },
    { id: '27', name: 'Ava', email: 'ava@example.com', semester: 'First' },
    { id: '28', name: 'Ben', email: 'ben@example.com', semester: 'Third' },
    { id: '29', name: 'Cleo', email: 'cleo@example.com', semester: 'First' },
    { id: '30', name: 'Derek', email: 'derek@example.com', semester: 'Third' },
    { id: '31', name: 'Ella', email: 'ella@example.com', semester: 'First' },
    { id: '32', name: 'Finn', email: 'finn@example.com', semester: 'Third' },
    { id: '33', name: 'Gina', email: 'gina@example.com', semester: 'First' },
    { id: '34', name: 'Hugo', email: 'hugo@example.com', semester: 'Third' },
    { id: '35', name: 'Iris', email: 'iris@example.com', semester: 'First' },
    { id: '36', name: 'Jake', email: 'jake@example.com', semester: 'Third' },
    { id: '37', name: 'Kira', email: 'kira@example.com', semester: 'First' },
    { id: '38', name: ' Leo', email: 'leo@example.com', semester: 'Third' },
    { id: '39', name: 'Maya', email: 'maya@example.com', semester: 'First' },
    { id: '40', name: 'Nina', email: 'nina@example.com', semester: 'Third' },
    { id: '41', name: 'Owen', email: 'owen@example.com', semester: 'First' },
    { id: '42', name: 'Penny', email: 'penny@example.com', semester: 'Third' },
    { id: '43', name: 'karki', email: 'penny@example.com', semester: 'Third' },
];